version: "3.2"

services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    container_name: backend
    volumes:
      - "./:/home/node/app"
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:12.8-alpine
    container_name: database
    ports:
      - "5432:5432"
    volumes:
      - "database_postgres:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: pagarme
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer:4.8.1
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  database_postgres:
    external: true
